#!/usr/bin/env node

import { createHash, randomUUID } from "node:crypto";
import {
  appendFile,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REFERENCES = path.join(ROOT, "references");

const AGENT_SKILLS_REPO = {
  name: "get-convex/agent-skills",
  branch: "main",
  expectedLicense: null,
};
const CONVEX_EVALS_REPO = {
  name: "get-convex/convex-evals",
  branch: "main",
  expectedLicense: "Apache-2.0",
};
const GUIDELINES_PATH = "runner/models/guidelines.md";

// On 2026-08-01 upstream regenerated its catalog from the convex-agents hub
// (get-convex/agent-skills#22). The hand-written task skills that this skill
// vendored were deleted or replaced by short generated procedures that depend
// on hub tooling (served capability catalog, recipes, findings bus, MCP tools)
// and drop the reference material bundled here. Those workflows are frozen at
// the last upstream commit that published them. Git history is immutable, so
// the frozen sources are still fetched and rendered by this script on every run.
export const FROZEN_UPSTREAM_COMMIT = "ec1e6baae7d86c7843c22938c75979c016f5c6e9";
export const FROZEN_ON = "2026-08-25";
export const FROZEN_REASON =
  "Upstream regenerated its catalog from the convex-agents hub on 2026-08-01 and replaced this skill with a short generated procedure that drops the reference material bundled here and, in most cases, depends on hub tooling.";

// Live task skills are tracked at the upstream default branch.
export const LIVE_SKILL_MAP = new Map([
  ["convex-create-component", "components.md"],
]);

// Frozen task skills are rendered from FROZEN_UPSTREAM_COMMIT.
export const FROZEN_SKILLS = new Map([
  [
    "convex-quickstart",
    { output: "quickstart.md", replacedBy: ["convex-quickstart"] },
  ],
  ["convex-setup-auth", { output: "auth.md", replacedBy: ["convex-auth"] }],
  [
    "convex-migration-helper",
    { output: "migrations.md", replacedBy: ["convex-migrate"] },
  ],
  [
    "convex-performance-audit",
    {
      output: "performance.md",
      replacedBy: ["convex-optimize", "convex-advisor"],
    },
  ],
]);

// Every upstream skill at the default branch needs a recorded decision. A new
// upstream skill without one fails synchronization until it is reviewed here.
const ROUTER_REASON =
  "Router. This skill owns routing and already bundles the material the router installs.";
const HUB_STUB_REASON =
  "Generated hub procedure added on 2026-08-01. It depends on convex-agents hub tooling and is not vendored.";
function replacementReason(frozenFolder) {
  const output = FROZEN_SKILLS.get(frozenFolder).output;
  return `Generated hub procedure that replaced ${frozenFolder} on 2026-08-01. The fuller pre-regeneration workflow is frozen as ${output}.`;
}
export const EXCLUDED_SKILLS = new Map([
  ["convex", ROUTER_REASON],
  ["convex-quickstart", replacementReason("convex-quickstart")],
  ["convex-auth", replacementReason("convex-setup-auth")],
  ["convex-migrate", replacementReason("convex-migration-helper")],
  ["convex-optimize", replacementReason("convex-performance-audit")],
  ["convex-advisor", replacementReason("convex-performance-audit")],
  ["convex-add", HUB_STUB_REASON],
  ["convex-agent", HUB_STUB_REASON],
  ["convex-authz", HUB_STUB_REASON],
  ["convex-backup", HUB_STUB_REASON],
  ["convex-billing", HUB_STUB_REASON],
  ["convex-cost", HUB_STUB_REASON],
  ["convex-crons", HUB_STUB_REASON],
  ["convex-deploy-guard", HUB_STUB_REASON],
  ["convex-design", HUB_STUB_REASON],
  ["convex-docs", HUB_STUB_REASON],
  ["convex-domains", HUB_STUB_REASON],
  ["convex-env", HUB_STUB_REASON],
  ["convex-expert", HUB_STUB_REASON],
  ["convex-explain-app", HUB_STUB_REASON],
  ["convex-improve-convex-plugin", HUB_STUB_REASON],
  ["convex-insights", HUB_STUB_REASON],
  ["convex-launch-readiness", HUB_STUB_REASON],
  ["convex-migrate-rehearse", HUB_STUB_REASON],
  ["convex-monitor", HUB_STUB_REASON],
  ["convex-reviewer", HUB_STUB_REASON],
  ["convex-seed", HUB_STUB_REASON],
  ["convex-self-heal", HUB_STUB_REASON],
  ["convex-sentinel", HUB_STUB_REASON],
  ["convex-suggest", HUB_STUB_REASON],
  ["convex-test", HUB_STUB_REASON],
  ["convex-verify", HUB_STUB_REASON],
]);

export const GENERATED_BANNER =
  "<!-- GENERATED by scripts/sync.mjs from upstream Convex sources. Do not edit by hand. -->";
const BUNDLED_GUIDANCE =
  "The Convex AI guidance is already bundled in this skill, so do not install another copy.";
const USER_AGENT = "convex-compendium-sync";
const FULL_SHA = /^[0-9a-f]{40}$/i;
const EXECUTABLE_INSTALLER =
  /(?:\b(?:npx(?:\s+-y)?|pnpm\s+(?:dlx|exec)|yarn\s+(?:dlx|exec)|bunx|npm\s+(?:exec|x)(?:\s+--)?)\s+)?convex(?:@[^\s`'\"]+)?(?:\s+--)?\s+ai-files\s+install\b/i;

export function normalizeText(value) {
  return value.replace(/\r\n?/g, "\n").replace(/\s+$/u, "") + "\n";
}

export function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

export function validateSkillDecisions() {
  const outputs = new Map();
  for (const [folder, output] of LIVE_SKILL_MAP) {
    if (FROZEN_SKILLS.has(folder)) {
      throw new Error(`${folder} is both live and frozen`);
    }
    if (EXCLUDED_SKILLS.has(folder)) {
      throw new Error(`${folder} is both live and excluded`);
    }
    if (outputs.has(output)) {
      throw new Error(`Two upstream skills map to ${output}`);
    }
    outputs.set(output, folder);
  }
  for (const [folder, config] of FROZEN_SKILLS) {
    if (outputs.has(config.output)) {
      throw new Error(`Two upstream skills map to ${config.output}`);
    }
    outputs.set(config.output, folder);
    for (const replacement of config.replacedBy) {
      if (!EXCLUDED_SKILLS.has(replacement)) {
        throw new Error(
          `${folder} names replacement ${replacement} without an exclusion decision`,
        );
      }
    }
  }
  if (outputs.has("guidelines.md") || outputs.has("source-manifest.json")) {
    throw new Error("A task skill maps to a reserved output name");
  }
  return outputs;
}

export function parseArgs(argv) {
  const options = {
    check: false,
    help: false,
    agentSkillsSha: null,
    convexEvalsSha: null,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--check") {
      options.check = true;
      continue;
    }
    if (argument === "--help" || argument === "-h") {
      options.help = true;
      continue;
    }
    if (
      argument === "--agent-skills-sha" ||
      argument === "--convex-evals-sha"
    ) {
      const value = argv[index + 1];
      if (!value || value.startsWith("-")) {
        throw new Error(`${argument} requires a full 40-character Git SHA`);
      }
      if (!FULL_SHA.test(value)) {
        throw new Error(`${argument} must be a full 40-character Git SHA`);
      }
      if (argument === "--agent-skills-sha") {
        options.agentSkillsSha = value.toLowerCase();
      } else {
        options.convexEvalsSha = value.toLowerCase();
      }
      index += 1;
      continue;
    }
    throw new Error(`Unknown argument: ${argument}`);
  }

  return options;
}

export function printHelp() {
  console.log(`Usage: node scripts/sync.mjs [OPTIONS]

Vendor Convex's official task skills and canonical guidelines into references/.
Requires Node 18+ and HTTPS access to api.github.com and
raw.githubusercontent.com. Set GITHUB_TOKEN to raise GitHub API rate limits.

Options:
  --check                    Compare generated output without writing
  --agent-skills-sha SHA     Pin get-convex/agent-skills to a full Git SHA
  --convex-evals-sha SHA     Pin get-convex/convex-evals to a full Git SHA
  -h, --help                 Show this help without network access

Live task skills follow the pinned or default-branch revision. Frozen task
skills are always rendered from ${FROZEN_UPSTREAM_COMMIT}.
The script owns every file in references/. It never edits SKILL.md or changes
metadata.version.`);
}

function headersForJson() {
  return {
    Accept: "application/vnd.github+json",
    "User-Agent": USER_AGENT,
    ...(process.env.GITHUB_TOKEN
      ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
      : {}),
  };
}

export async function fetchValidated(
  url,
  { expectedHost, acceptJson = false, fetchImpl = fetch } = {},
) {
  const requested = new URL(url);
  if (requested.protocol !== "https:") {
    throw new Error(`Refusing non-HTTPS source: ${url}`);
  }

  const response = await fetchImpl(url, {
    redirect: "follow",
    headers: acceptJson ? headersForJson() : { "User-Agent": USER_AGENT },
  });
  const finalUrl = new URL(response.url || url);
  if (finalUrl.protocol !== "https:" || finalUrl.hostname !== expectedHost) {
    throw new Error(
      `GET ${url} finished on unexpected host ${finalUrl.hostname || "unknown"}`,
    );
  }
  if (!response.ok) {
    const detail = (await response.text()).slice(0, 500).replace(/\s+/g, " ");
    throw new Error(
      `GET ${url} returned ${response.status} ${response.statusText}${detail ? `: ${detail}` : ""}`,
    );
  }
  return response;
}

async function fetchJson(url, fetchImpl) {
  const response = await fetchValidated(url, {
    expectedHost: "api.github.com",
    acceptJson: true,
    fetchImpl,
  });
  return response.json();
}

async function fetchText(url, fetchImpl) {
  const response = await fetchValidated(url, {
    expectedHost: "raw.githubusercontent.com",
    fetchImpl,
  });
  return normalizeText(await response.text());
}

function validateCommit(value, repo) {
  if (!value || !FULL_SHA.test(value.sha ?? "")) {
    throw new Error(`${repo} returned an invalid commit response`);
  }
  return value.sha.toLowerCase();
}

export function validateTree(value, repo) {
  if (!value || !Array.isArray(value.tree)) {
    throw new Error(`${repo} returned an invalid Git tree`);
  }
  if (value.truncated === true) {
    throw new Error(`${repo} returned a truncated Git tree`);
  }
  const blobs = new Map();
  for (const entry of value.tree) {
    if (
      entry?.type === "blob" &&
      typeof entry.path === "string" &&
      FULL_SHA.test(entry.sha ?? "")
    ) {
      blobs.set(entry.path, entry.sha.toLowerCase());
    }
  }
  return blobs;
}

export async function inspectRevision(config, commitRef, fetchImpl) {
  const commit = await fetchJson(
    `https://api.github.com/repos/${config.name}/commits/${commitRef}`,
    fetchImpl,
  );
  const sha = validateCommit(commit, config.name);
  if (FULL_SHA.test(commitRef) && sha !== commitRef.toLowerCase()) {
    throw new Error(
      `${config.name} resolved ${commitRef} to unexpected commit ${sha}`,
    );
  }

  const tree = await fetchJson(
    `https://api.github.com/repos/${config.name}/git/trees/${sha}?recursive=1`,
    fetchImpl,
  );

  return { name: config.name, sha, blobs: validateTree(tree, config.name) };
}

export async function inspectRepository(config, suppliedSha, fetchImpl) {
  const metadata = await fetchJson(
    `https://api.github.com/repos/${config.name}`,
    fetchImpl,
  );
  if (
    typeof metadata.default_branch !== "string" ||
    typeof metadata.html_url !== "string"
  ) {
    throw new Error(`${config.name} returned invalid repository metadata`);
  }

  const license = metadata.license?.spdx_id ?? null;
  if (config.expectedLicense && license !== config.expectedLicense) {
    throw new Error(
      `${config.name} license is ${license ?? "not detected"}, expected ${config.expectedLicense}`,
    );
  }

  const revision = await inspectRevision(
    config,
    suppliedSha ?? metadata.default_branch,
    fetchImpl,
  );

  return {
    name: config.name,
    url: metadata.html_url,
    defaultBranch: metadata.default_branch,
    license,
    sha: revision.sha,
    blobs: revision.blobs,
  };
}

function discoverSkills(blobs) {
  const discovered = new Set();
  for (const sourcePath of blobs.keys()) {
    const match = sourcePath.match(/^skills\/(convex[^/]*)\/SKILL\.md$/);
    if (match) discovered.add(match[1]);
  }
  return discovered;
}

function collectSkillSources(folder, blobs, output) {
  const skillPath = `skills/${folder}/SKILL.md`;
  if (!blobs.has(skillPath)) {
    throw new Error(`Required source is missing: ${skillPath}`);
  }
  const prefix = `skills/${folder}/references/`;
  const references = [];
  for (const sourcePath of blobs.keys()) {
    if (!sourcePath.startsWith(prefix)) continue;
    const relative = sourcePath.slice(prefix.length);
    if (!relative.endsWith(".md") || relative.includes("/")) {
      throw new Error(
        `Expected one-level Markdown references for ${folder}, found ${sourcePath}`,
      );
    }
    references.push(sourcePath);
  }
  references.sort();
  return { skillPath, references, output };
}

export function validateSourceShape(agentBlobs, frozenBlobs, evalBlobs) {
  validateSkillDecisions();

  const discovered = discoverSkills(agentBlobs);
  for (const name of LIVE_SKILL_MAP.keys()) {
    if (!discovered.has(name)) {
      throw new Error(`Required upstream Convex skill is missing: ${name}`);
    }
  }
  for (const name of discovered) {
    if (LIVE_SKILL_MAP.has(name) || EXCLUDED_SKILLS.has(name)) continue;
    if (FROZEN_SKILLS.has(name)) {
      throw new Error(
        `Frozen upstream Convex skill reappeared and requires review: ${name}`,
      );
    }
    throw new Error(`Unmapped upstream Convex skill requires review: ${name}`);
  }
  const namedReplacements = new Set(
    [...FROZEN_SKILLS.values()].flatMap((config) => config.replacedBy),
  );
  for (const name of EXCLUDED_SKILLS.keys()) {
    if (discovered.has(name)) continue;
    if (namedReplacements.has(name)) {
      throw new Error(
        `Replacement upstream Convex skill disappeared and requires review: ${name}`,
      );
    }
    console.warn(
      `exclusion decision for ${name} no longer matches an upstream skill`,
    );
  }

  const frozenDiscovered = discoverSkills(frozenBlobs);
  for (const name of FROZEN_SKILLS.keys()) {
    if (!frozenDiscovered.has(name)) {
      throw new Error(
        `Frozen upstream Convex skill is missing at ${FROZEN_UPSTREAM_COMMIT}: ${name}`,
      );
    }
  }

  const sourcesBySkill = new Map();
  for (const [folder, output] of LIVE_SKILL_MAP) {
    sourcesBySkill.set(folder, {
      ...collectSkillSources(folder, agentBlobs, output),
      frozen: null,
    });
  }
  for (const [folder, config] of FROZEN_SKILLS) {
    // Replacement blob SHAs are recorded so an upstream rewrite of a
    // replacement surfaces as a manifest change instead of passing unseen.
    const replacementBlobs = {};
    for (const name of config.replacedBy) {
      replacementBlobs[name] = agentBlobs.get(`skills/${name}/SKILL.md`);
    }
    sourcesBySkill.set(folder, {
      ...collectSkillSources(folder, frozenBlobs, config.output),
      frozen: {
        commit: FROZEN_UPSTREAM_COMMIT,
        frozenOn: FROZEN_ON,
        replacedBy: [...config.replacedBy],
        replacementBlobs,
      },
    });
  }

  if (!evalBlobs.has(GUIDELINES_PATH)) {
    throw new Error(`Required source is missing: ${GUIDELINES_PATH}`);
  }

  return sourcesBySkill;
}

export function parseSkillSource(markdown, expectedName) {
  const normalized = normalizeText(markdown);
  if (!normalized.startsWith("---\n")) {
    throw new Error(`${expectedName} SKILL.md has no YAML frontmatter`);
  }
  const end = normalized.indexOf("\n---\n", 4);
  if (end < 0) {
    throw new Error(`${expectedName} SKILL.md has malformed YAML frontmatter`);
  }
  const frontmatter = normalized.slice(4, end);
  const nameMatch = frontmatter.match(/^name:\s*["']?([^"'\n]+)["']?\s*$/m);
  if (!nameMatch || nameMatch[1].trim() !== expectedName) {
    throw new Error(`${expectedName} SKILL.md has mismatched frontmatter name`);
  }
  const body = normalized.slice(end + 5).trimStart();
  if (!/^#\s+\S/m.test(body) || !body.startsWith("# ")) {
    throw new Error(`${expectedName} SKILL.md must begin with an H1`);
  }
  return normalizeText(body);
}

export function stripLeadingH1(markdown) {
  const normalized = normalizeText(markdown);
  if (!normalized.startsWith("# ")) {
    throw new Error("Expected Markdown to begin with an H1");
  }
  const newline = normalized.indexOf("\n");
  return normalizeText(normalized.slice(newline + 1).trimStart());
}

function slugifyHeading(value) {
  return value
    .toLowerCase()
    .replace(/<[^>]+>/g, "")
    .replace(/[`*_~]/g, "")
    .replace(/[^\p{L}\p{N}\s-]/gu, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

function transformLinesOutsideFences(markdown, transform) {
  let fenced = false;
  let marker = null;
  return markdown
    .split("\n")
    .map((line) => {
      const fence = line.match(/^\s*(```+|~~~+)/);
      if (fence) {
        const current = fence[1][0];
        if (!fenced) {
          fenced = true;
          marker = current;
        } else if (current === marker) {
          fenced = false;
          marker = null;
        }
        return line;
      }
      return fenced ? line : transform(line);
    })
    .join("\n");
}

export function namespaceHeadings(markdown, namespace, levels = 2) {
  const seen = new Map();
  const anchors = new Map();
  const lines = markdown.split("\n");
  let fenced = false;
  let marker = null;
  const output = [];

  for (const line of lines) {
    const fence = line.match(/^\s*(```+|~~~+)/);
    if (fence) {
      const current = fence[1][0];
      if (!fenced) {
        fenced = true;
        marker = current;
      } else if (current === marker) {
        fenced = false;
        marker = null;
      }
      output.push(line);
      continue;
    }

    const heading = !fenced ? line.match(/^(#{1,6})\s+(.+?)\s*$/) : null;
    if (!heading) {
      output.push(line);
      continue;
    }

    const base = slugifyHeading(heading[2]);
    if (!base)
      throw new Error(`Cannot generate an anchor for heading: ${line}`);
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    const original = count === 0 ? base : `${base}-${count}`;
    const anchor = `${namespace}-${original}`;
    anchors.set(original, anchor);
    output.push(`<a id="${anchor}"></a>`);
    const depth = Math.min(6, heading[1].length + levels);
    output.push(`${"#".repeat(depth)} ${heading[2]}`);
  }

  return { markdown: output.join("\n"), anchors };
}

function targetForReference(name, fragment, referenceInfo) {
  const info = referenceInfo.get(name);
  if (!info)
    throw new Error(`Link points to unknown flattened reference: ${name}`);
  if (!fragment) return `#${info.rootAnchor}`;
  const decoded = decodeURIComponent(fragment);
  const slug = slugifyHeading(decoded);
  const anchor = info.anchors.get(decoded) ?? info.anchors.get(slug);
  if (!anchor) {
    throw new Error(`Link points to unknown heading ${name}.md#${fragment}`);
  }
  return `#${anchor}`;
}

export function rewriteReferenceLinks(markdown, referenceInfo) {
  return transformLinesOutsideFences(markdown, (line) => {
    let rewritten = line.replace(
      /\((?:\.\/)?references\/([^/#\s)]+)\.md(?:#([^\s)"']+))?(\s+["'][^"']*["'])?\)/g,
      (_match, name, fragment, title = "") =>
        `(${targetForReference(name, fragment, referenceInfo)}${title})`,
    );
    rewritten = rewritten.replace(
      /`(?:\.\/)?references\/([^/#`\s]+)\.md(?:#([^`\s]+))?`/g,
      (_match, name, fragment) => {
        const target = targetForReference(name, fragment, referenceInfo);
        return `[${fragment ? `${name} section` : name}](${target})`;
      },
    );
    return rewritten;
  });
}

export function neutralizeInstallerCommands(markdown) {
  let fenced = false;
  let marker = null;
  let replaced = false;
  const lines = markdown.split("\n").map((line) => {
    const fence = line.match(/^\s*(```+|~~~+)/);
    if (fence) {
      const current = fence[1][0];
      if (!fenced) {
        fenced = true;
        marker = current;
      } else if (current === marker) {
        fenced = false;
        marker = null;
      }
      return line;
    }
    if (!EXECUTABLE_INSTALLER.test(line)) return line;
    replaced = true;
    return fenced ? `# ${BUNDLED_GUIDANCE}` : BUNDLED_GUIDANCE;
  });
  return { markdown: lines.join("\n"), replaced };
}

export function assertNoExecutableInstaller(markdown, label = "output") {
  if (EXECUTABLE_INSTALLER.test(markdown)) {
    throw new Error(
      `${label} still contains an executable ai-files installer command`,
    );
  }
}

function assertNoUnresolvedReferences(markdown, label) {
  const prose = transformLinesOutsideFences(markdown, (line) => line);
  if (
    /\((?:\.\/)?references\/[^)]+\.md/i.test(prose) ||
    /`(?:\.\/)?references\/[^`]+\.md/i.test(prose)
  ) {
    throw new Error(
      `${label} still contains an unresolved local reference link`,
    );
  }
}

export function validateGuidelines(markdown) {
  const normalized = normalizeText(markdown);
  if (!normalized.startsWith("# Convex guidelines\n")) {
    throw new Error(
      "Canonical guidelines no longer begin with the expected H1",
    );
  }
  const version = normalized.match(
    /These guidelines target Convex `([^`]+)`\./,
  )?.[1];
  if (!version) {
    throw new Error(
      "Canonical guidelines no longer declare a target Convex range",
    );
  }
  for (const topic of [
    "function",
    "schema",
    "authentication",
    "query",
    "mutation",
    "action",
  ]) {
    if (!new RegExp(`\\b${topic}s?\\b`, "i").test(normalized)) {
      throw new Error(`Canonical guidelines no longer cover ${topic}`);
    }
  }
  return version;
}

function frozenNotice(frozen) {
  const replacements = frozen.replacedBy
    .map((name) => `\`${name}\``)
    .join(" and ");
  return `> Frozen on ${frozen.frozenOn} at upstream commit ${frozen.commit}, the last revision that published this skill. Upstream replaced it with the short generated ${replacements} procedure, which drops the reference material bundled here. The source manifest records this freeze.`;
}

function provenanceHeader(title, sourceUrl, frozen = null) {
  const notices = [];
  if (frozen) notices.push(frozenNotice(frozen));
  notices.push(`> ${BUNDLED_GUIDANCE}`);
  return `${GENERATED_BANNER}\n\n# ${title}\n\n_Source: <${sourceUrl}>_\n\n${notices.join("\n\n")}\n`;
}

function titleForSkill(folder) {
  return folder
    .replace(/^convex-/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

export function renderTaskReference({
  folder,
  skillBody,
  references,
  frozen = null,
}) {
  const referenceInfo = new Map();
  const prepared = [];

  for (const reference of references) {
    const name = path.basename(reference.path, ".md");
    if (referenceInfo.has(name)) {
      throw new Error(`Duplicate flattened reference name: ${name}`);
    }
    const rootAnchor = `reference-${slugifyHeading(name)}`;
    const namespaced = namespaceHeadings(
      normalizeText(reference.body).trim(),
      rootAnchor,
      2,
    );
    referenceInfo.set(name, {
      rootAnchor,
      anchors: namespaced.anchors,
    });
    prepared.push({ name, rootAnchor, markdown: namespaced.markdown });
  }

  let body = stripLeadingH1(parseSkillSource(skillBody, folder));
  body = rewriteReferenceLinks(body, referenceInfo);
  body = neutralizeInstallerCommands(body).markdown;

  for (const reference of prepared) {
    let subBody = rewriteReferenceLinks(reference.markdown, referenceInfo);
    subBody = neutralizeInstallerCommands(subBody).markdown;
    body += `\n---\n\n<a id="${reference.rootAnchor}"></a>\n\n## Reference: ${reference.name}\n\n${subBody.trim()}\n`;
  }

  const revision = frozen ? frozen.commit : AGENT_SKILLS_REPO.branch;
  const sourceUrl = `https://github.com/${AGENT_SKILLS_REPO.name}/tree/${revision}/skills/${folder}`;
  const output = normalizeText(
    `${provenanceHeader(`Convex ${titleForSkill(folder)}`, sourceUrl, frozen)}\n${body.trim()}`,
  );
  assertNoExecutableInstaller(output, folder);
  assertNoUnresolvedReferences(output, folder);
  return output;
}

export function renderGuidelines(markdown) {
  validateGuidelines(markdown);
  const body = stripLeadingH1(markdown);
  const sourceUrl = `https://github.com/${CONVEX_EVALS_REPO.name}/blob/${CONVEX_EVALS_REPO.branch}/${GUIDELINES_PATH}`;
  const output = normalizeText(
    `${provenanceHeader("Convex Guidelines", sourceUrl)}\n${body.trim()}`,
  );
  assertNoExecutableInstaller(output, "guidelines.md");
  return output;
}

function repositoryManifest(snapshot) {
  return {
    name: snapshot.name,
    url: snapshot.url,
    defaultBranch: snapshot.defaultBranch,
    license: {
      spdx: snapshot.license,
      status:
        snapshot.license === null
          ? "no explicit repository license detected"
          : "detected",
    },
  };
}

function frozenManifest(taskSources) {
  const frozen = {};
  for (const [folder, config] of FROZEN_SKILLS) {
    const replacementBlobs = taskSources.get(folder)?.frozen?.replacementBlobs;
    frozen[folder] = {
      output: config.output,
      pinnedCommit: FROZEN_UPSTREAM_COMMIT,
      frozenOn: FROZEN_ON,
      replacedBy: [...config.replacedBy],
      replacementBlobs: Object.fromEntries(
        config.replacedBy.map((name) => [
          name,
          replacementBlobs?.[name] ?? null,
        ]),
      ),
      reason: FROZEN_REASON,
    };
  }
  return frozen;
}

export function buildManifest({
  agentSnapshot,
  evalSnapshot,
  targetRange,
  consumedSources,
  outputSources,
  markdownOutputs,
  taskSources = new Map(),
}) {
  const sources = [...consumedSources]
    .sort((a, b) => a.path.localeCompare(b.path))
    .map((source) => ({
      repository: source.repository,
      path: source.path,
      ...(source.pinnedCommit ? { pinnedCommit: source.pinnedCommit } : {}),
      blobSha: source.blobSha,
      sha256: sha256(source.body),
    }));
  const outputs = [...markdownOutputs.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([outputPath, body]) => ({
      path: `references/${outputPath}`,
      sha256: sha256(body),
      sources: [...outputSources.get(outputPath)].sort(),
    }));

  return normalizeText(
    JSON.stringify(
      {
        formatVersion: 2,
        generated: true,
        generator: "scripts/sync.mjs",
        repositories: [
          repositoryManifest(agentSnapshot),
          repositoryManifest(evalSnapshot),
        ].sort((a, b) => a.name.localeCompare(b.name)),
        taskSkills: {
          mapped: Object.fromEntries(LIVE_SKILL_MAP),
          frozen: frozenManifest(taskSources),
          excluded: Object.fromEntries(
            [...EXCLUDED_SKILLS].sort(([a], [b]) => a.localeCompare(b)),
          ),
        },
        guidelines: {
          path: GUIDELINES_PATH,
          targetConvexRange: targetRange,
        },
        sources,
        outputs,
      },
      null,
      2,
    ),
  );
}

async function readPreviousManifest(referenceDir = REFERENCES) {
  try {
    return JSON.parse(
      await readFile(path.join(referenceDir, "source-manifest.json"), "utf8"),
    );
  } catch (error) {
    if (error?.code === "ENOENT" || error instanceof SyntaxError) return null;
    throw error;
  }
}

function reportLicenseDrift(previous, current) {
  if (!previous?.repositories) return;
  const oldLicenses = new Map(
    previous.repositories.map((repo) => [
      repo.name,
      repo.license?.spdx ?? null,
    ]),
  );
  for (const repo of current.repositories) {
    if (
      oldLicenses.has(repo.name) &&
      oldLicenses.get(repo.name) !== repo.license.spdx
    ) {
      console.warn(
        `license changed for ${repo.name}: ${oldLicenses.get(repo.name) ?? "not detected"} -> ${repo.license.spdx ?? "not detected"}`,
      );
    }
  }
}

export async function compareOutputs(
  outputs,
  referenceDir = REFERENCES,
  fsApi = { readFile, readdir },
) {
  let entries = [];
  try {
    entries = await fsApi.readdir(referenceDir, { withFileTypes: true });
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  const actualFiles = new Set(
    entries.filter((entry) => entry.isFile()).map((entry) => entry.name),
  );
  const actualEntries = new Map(
    entries.map((entry) => [entry.name, entry.isFile()]),
  );
  const expectedFiles = new Set(outputs.keys());
  const missing = [];
  const changed = [];
  const stale = [];

  for (const [name, expected] of outputs) {
    if (!actualFiles.has(name)) {
      missing.push(name);
      continue;
    }
    const actual = await fsApi.readFile(path.join(referenceDir, name), "utf8");
    if (actual !== expected) changed.push(name);
  }
  for (const [name, isFile] of actualEntries) {
    if (!expectedFiles.has(name) || !isFile) stale.push(name);
  }

  return {
    missing: missing.sort(),
    changed: changed.sort(),
    stale: stale.sort(),
  };
}

function isCurrent(diff) {
  return (
    diff.missing.length === 0 &&
    diff.changed.length === 0 &&
    diff.stale.length === 0
  );
}

function describeDiff(diff) {
  const lines = [];
  if (diff.missing.length) lines.push(`missing: ${diff.missing.join(", ")}`);
  if (diff.changed.length) lines.push(`changed: ${diff.changed.join(", ")}`);
  if (diff.stale.length) lines.push(`stale: ${diff.stale.join(", ")}`);
  return lines.join("\n");
}

export async function assertSafeExistingFiles(
  outputs,
  referenceDir,
  previousManifest,
) {
  let entries = [];
  try {
    entries = await readdir(referenceDir, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return;
    throw error;
  }
  const previouslyOwned = new Set(
    (previousManifest?.outputs ?? []).map((output) =>
      path.basename(output.path),
    ),
  );
  previouslyOwned.add("source-manifest.json");

  for (const entry of entries) {
    if (!entry.isFile()) {
      throw new Error(
        `Refusing to replace unrecognized reference entry: ${entry.name}`,
      );
    }
    if (outputs.has(entry.name) || previouslyOwned.has(entry.name)) {
      continue;
    }
    const body = await readFile(path.join(referenceDir, entry.name), "utf8");
    if (!body.startsWith(GENERATED_BANNER)) {
      throw new Error(
        `Refusing to replace unrecognized hand-authored reference: ${entry.name}`,
      );
    }
  }
}

export async function replaceDirectoryAtomic(
  targetDir,
  outputs,
  fsApi = { mkdir, writeFile, rename, rm },
) {
  const parent = path.dirname(targetDir);
  const token = `${process.pid}-${randomUUID()}`;
  const staging = path.join(parent, `.references-sync-${token}`);
  const backup = path.join(parent, `.references-backup-${token}`);
  let movedExisting = false;

  await fsApi.mkdir(staging, { recursive: true });
  try {
    for (const [name, body] of outputs) {
      await fsApi.writeFile(path.join(staging, name), body, "utf8");
    }
    try {
      await fsApi.rename(targetDir, backup);
      movedExisting = true;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    try {
      await fsApi.rename(staging, targetDir);
    } catch (error) {
      if (movedExisting) await fsApi.rename(backup, targetDir);
      throw error;
    }
    if (movedExisting) await fsApi.rm(backup, { recursive: true, force: true });
  } finally {
    await fsApi.rm(staging, { recursive: true, force: true });
  }
}

async function writeGitHubOutput(agentSkillsSha, convexEvalsSha) {
  if (!process.env.GITHUB_OUTPUT) return;
  await appendFile(
    process.env.GITHUB_OUTPUT,
    `agent_skills_sha=${agentSkillsSha}\nconvex_evals_sha=${convexEvalsSha}\n`,
  );
}

export async function generate({
  agentSkillsSha = null,
  convexEvalsSha = null,
  check = false,
  fetchImpl = fetch,
  referenceDir = REFERENCES,
} = {}) {
  const [agentSnapshot, frozenSnapshot, evalSnapshot] = await Promise.all([
    inspectRepository(AGENT_SKILLS_REPO, agentSkillsSha, fetchImpl),
    inspectRevision(AGENT_SKILLS_REPO, FROZEN_UPSTREAM_COMMIT, fetchImpl),
    inspectRepository(CONVEX_EVALS_REPO, convexEvalsSha, fetchImpl),
  ]);

  const sourceMap = validateSourceShape(
    agentSnapshot.blobs,
    frozenSnapshot.blobs,
    evalSnapshot.blobs,
  );
  const rawUrl = (repo, sha, sourcePath) =>
    `https://raw.githubusercontent.com/${repo}/${sha}/${sourcePath}`;
  const required = [];
  for (const { skillPath, references, frozen } of sourceMap.values()) {
    const snapshot = frozen ? frozenSnapshot : agentSnapshot;
    for (const sourcePath of [skillPath, ...references]) {
      required.push({
        repository: snapshot.name,
        sha: snapshot.sha,
        pinnedCommit: frozen ? frozen.commit : null,
        path: sourcePath,
        blobSha: snapshot.blobs.get(sourcePath),
      });
    }
  }
  required.push({
    repository: evalSnapshot.name,
    sha: evalSnapshot.sha,
    pinnedCommit: null,
    path: GUIDELINES_PATH,
    blobSha: evalSnapshot.blobs.get(GUIDELINES_PATH),
  });

  const consumedSources = await Promise.all(
    required.map(async (source) => ({
      ...source,
      body: await fetchText(
        rawUrl(source.repository, source.sha, source.path),
        fetchImpl,
      ),
    })),
  );
  const bodies = new Map(
    consumedSources.map((source) => [
      `${source.repository}:${source.sha}:${source.path}`,
      source.body,
    ]),
  );

  const markdownOutputs = new Map();
  const outputSources = new Map();
  for (const [folder, config] of sourceMap) {
    const sha = config.frozen ? config.frozen.commit : agentSnapshot.sha;
    const skillBody = bodies.get(
      `${agentSnapshot.name}:${sha}:${config.skillPath}`,
    );
    const references = config.references.map((sourcePath) => ({
      path: sourcePath,
      body: bodies.get(`${agentSnapshot.name}:${sha}:${sourcePath}`),
    }));
    markdownOutputs.set(
      config.output,
      renderTaskReference({
        folder,
        skillBody,
        references,
        frozen: config.frozen,
      }),
    );
    outputSources.set(config.output, [config.skillPath, ...config.references]);
  }

  const guidelinesBody = bodies.get(
    `${evalSnapshot.name}:${evalSnapshot.sha}:${GUIDELINES_PATH}`,
  );
  const targetRange = validateGuidelines(guidelinesBody);
  markdownOutputs.set("guidelines.md", renderGuidelines(guidelinesBody));
  outputSources.set("guidelines.md", [GUIDELINES_PATH]);

  const manifestBody = buildManifest({
    agentSnapshot,
    evalSnapshot,
    targetRange,
    consumedSources,
    outputSources,
    markdownOutputs,
    taskSources: sourceMap,
  });
  const outputs = new Map(markdownOutputs);
  outputs.set("source-manifest.json", manifestBody);

  for (const [name, body] of outputs) {
    if (!body.endsWith("\n")) throw new Error(`${name} has no final newline`);
    if (name.endsWith(".md") && !body.startsWith(GENERATED_BANNER)) {
      throw new Error(`${name} has no generated-file banner`);
    }
  }

  const previousManifest = await readPreviousManifest(referenceDir);
  const currentManifest = JSON.parse(manifestBody);
  reportLicenseDrift(previousManifest, currentManifest);
  if (agentSnapshot.license === null) {
    console.warn(
      `${agentSnapshot.name}: no explicit repository license detected; retaining the approved vendored task model`,
    );
  } else {
    console.warn(
      `${agentSnapshot.name}: repository license ${agentSnapshot.license} is now detected; review the source policy before publication`,
    );
  }

  const diff = await compareOutputs(outputs, referenceDir);
  if (check) {
    if (!isCurrent(diff)) {
      throw new Error(
        `Generated references are not current:\n${describeDiff(diff)}`,
      );
    }
  } else if (!isCurrent(diff)) {
    await assertSafeExistingFiles(outputs, referenceDir, previousManifest);
    await replaceDirectoryAtomic(referenceDir, outputs);
  }

  console.log(
    `${check ? "checked" : isCurrent(diff) ? "unchanged" : "updated"} references/`,
  );
  console.log(`upstream ${agentSnapshot.name} @ ${agentSnapshot.sha}`);
  console.log(
    `frozen ${agentSnapshot.name} @ ${frozenSnapshot.sha} for ${[...FROZEN_SKILLS.keys()].join(", ")}`,
  );
  console.log(`upstream ${evalSnapshot.name} @ ${evalSnapshot.sha}`);
  console.log(`guidelines target Convex ${targetRange}`);
  await writeGitHubOutput(agentSnapshot.sha, evalSnapshot.sha);

  return {
    agentSkillsSha: agentSnapshot.sha,
    frozenAgentSkillsSha: frozenSnapshot.sha,
    convexEvalsSha: evalSnapshot.sha,
    targetRange,
    diff,
    outputs,
  };
}

export async function main(argv = process.argv.slice(2)) {
  const options = parseArgs(argv);
  if (options.help) {
    printHelp();
    return;
  }
  await generate(options);
}

const isEntryPoint =
  process.argv[1] &&
  pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url;
if (isEntryPoint) {
  main().catch((error) => {
    console.error(`Error: ${error.message}`);
    process.exitCode = 1;
  });
}
