#!/usr/bin/env node
// Vendors Convex's upstream AI guidance into this skill so it travels with a
// single submodule. Run by .github/workflows/sync-upstream.yml and locally.
//
// Sources (see AGENTS.md "Sources of truth"):
//   - Task skills: github.com/get-convex/agent-skills      -> references/<task>.md
//   - Rules body:  https://convex.link/convex_rules.txt   -> references/guidelines.md
//
// Provenance lives in git history: the workflow records the upstream commit in
// the sync commit message. This script never edits SKILL.md metadata.version.

import { mkdir, writeFile, appendFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REFS = path.join(ROOT, "references");

const RULES_URL = "https://convex.link/convex_rules.txt";
const SKILLS_REPO = "get-convex/agent-skills";
const SKILLS_BRANCH = "main";

// Upstream skill folder -> our reference filename. The `convex` router is
// intentionally excluded: our SKILL.md replaces its routing, and its only job
// is to recommend `ai-files install`, which we deliberately avoid.
const SKILL_MAP = {
  "convex-quickstart": "quickstart",
  "convex-setup-auth": "auth",
  "convex-create-component": "components",
  "convex-migration-helper": "migrations",
  "convex-performance-audit": "performance",
};

const GENERATED_BANNER =
  "<!-- GENERATED by scripts/sync.mjs from upstream Convex sources. Do not edit by hand; edit the sync script or re-run it. -->";

const BUNDLED_NOTE =
  "> These Convex AI guidelines are already bundled in this skill (see `references/guidelines.md`). Do not run the Convex `ai-files` installer; it clutters the project and installs per-agent skill copies this skill already provides.";

async function getJson(url) {
  const res = await fetch(url, {
    headers: {
      "User-Agent": "convex-compendium-sync",
      Accept: "application/vnd.github+json",
      ...(process.env.GITHUB_TOKEN
        ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
        : {}),
    },
  });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return res.json();
}

async function getText(url) {
  const res = await fetch(url, {
    headers: { "User-Agent": "convex-compendium-sync" },
  });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
  return res.text();
}

// Remove leading YAML frontmatter so a vendored skill body reads as a plain
// reference, not a nested skill.
function stripFrontmatter(md) {
  if (md.startsWith("---")) {
    const end = md.indexOf("\n---", 3);
    if (end !== -1) {
      const after = md.indexOf("\n", end + 1);
      return md.slice(after + 1).replace(/^\s+/, "");
    }
  }
  return md;
}

// Neutralize any recommendation to run the installer we are replacing.
function rewriteAiFiles(md) {
  return md.replace(
    /`?npx convex ai-files install`?/g,
    "(bundled in this skill — do not run the ai-files installer)",
  );
}

// Drop a body's own leading H1 so it does not duplicate our provenance title.
function stripLeadingH1(md) {
  return md.replace(/^\s*#\s+.*(\r?\n)+/, "");
}

// Push a sub-reference's headings deeper so they nest under our "## Reference"
// heading and keep one clean outline.
function demoteHeadings(md, levels = 2) {
  const extra = "#".repeat(levels);
  return md.replace(/^(#{1,5})(\s)/gm, (_, hashes, sp) => `${hashes}${extra}${sp}`);
}

// Header carries the source path but no commit SHA, so a reference only changes
// when its actual content changes - the exact upstream commit lives in git.
function provenanceHeader(title, source) {
  return `${GENERATED_BANNER}\n\n# ${title}\n\n_Source: ${source}_\n\n${BUNDLED_NOTE}\n`;
}

async function main() {
  await mkdir(REFS, { recursive: true });

  // Resolve the upstream commit so every raw fetch in this run is consistent.
  const commit = await getJson(
    `https://api.github.com/repos/${SKILLS_REPO}/commits/${SKILLS_BRANCH}`,
  );
  const sha = commit.sha;
  const raw = (p) =>
    `https://raw.githubusercontent.com/${SKILLS_REPO}/${sha}/${p}`;

  const tree = await getJson(
    `https://api.github.com/repos/${SKILLS_REPO}/git/trees/${sha}?recursive=1`,
  );
  const paths = tree.tree.filter((t) => t.type === "blob").map((t) => t.path);

  // 1) Each task skill -> a single flattened reference
  for (const [folder, outName] of Object.entries(SKILL_MAP)) {
    const skillFile = `skills/${folder}/SKILL.md`;
    if (!paths.includes(skillFile)) {
      console.warn(`! upstream skill missing: ${folder} (skipping)`);
      continue;
    }
    const refFiles = paths
      .filter((p) => p.startsWith(`skills/${folder}/references/`) && p.endsWith(".md"))
      .sort();

    let body = stripLeadingH1(stripFrontmatter(await getText(raw(skillFile))));
    for (const rf of refFiles) {
      const name = path.basename(rf, ".md");
      const sub = demoteHeadings((await getText(raw(rf))).trim());
      body += `\n\n---\n\n## Reference: ${name}\n\n${sub}\n`;
    }
    body = rewriteAiFiles(body);

    const source = `${SKILLS_REPO}/skills/${folder}`;
    const title = folder
      .replace(/^convex-/, "")
      .replace(/-/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());
    await writeFile(
      path.join(REFS, `${outName}.md`),
      `${provenanceHeader(`Convex ${title}`, source)}\n${body.trim()}\n`,
      "utf8",
    );
    console.log(`wrote references/${outName}.md (from ${folder})`);
  }

  // 2) Rules body -> guidelines.md
  const rulesBody = await getText(RULES_URL);
  await writeFile(
    path.join(REFS, "guidelines.md"),
    `${provenanceHeader("Convex Guidelines", RULES_URL)}\n${rulesBody.trim()}\n`,
    "utf8",
  );
  console.log("wrote references/guidelines.md");

  // Hand the exact upstream commit to the workflow for the commit message.
  console.log(`upstream get-convex/agent-skills @ ${sha}`);
  if (process.env.GITHUB_OUTPUT) {
    await appendFile(process.env.GITHUB_OUTPUT, `upstream_sha=${sha}\n`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
